export const getImageSource = (name) => {
    const imageMap = {
      "Peasant"                       : require("../../assets/Characters/KA.Peasant.png"),
      "Mercenary"                     : require("../../assets/Characters/KA.Mercenary.png"),
      "Monk"                          : require("../../assets/Characters/KA.Monk.png"),
      "Archer"                        : require("../../assets/Characters/KA.Archer.png"),
      "Swordman"                      : require("../../assets/Characters/KA.Swordman.png"),
      "Priest"                        : require("../../assets/Characters/KA.Priest.png"),
      "Swordmaster Gauss"             : require("../../assets/Characters/KA.SwordmasterGauss.png"),
      "Gold Arrow Archis"             : require("../../assets/Characters/KA.GoldenArrowArchis.png"),
      "Paladin Thorne"                : require("../../assets/Characters/KA.PaladinThorne.png"),
      "King Amos"                     : require("../../assets/Characters/KA.KingAmosThe3rd.png"),
      "Elf Civilian"                  : require("../../assets/Characters/WW.ElfCivilian.png"),
      "Elf Archer"                    : require("../../assets/Characters/WW.ElfArcher.png"),
      "Elf Mage"                      : require("../../assets/Characters/WW.ElfMage.png"),
      "Elf Guard"                     : require("../../assets/Characters/WW.ElfGuard.png"),
      "Elven Prince Eridan"           : require("../../assets/Characters/WW.ElvenPrinceEridan.png"),
      "Orc brute"                     : require("../../assets/Characters/WW.OrcBrute.png"),
      "Orc shaman"                    : require("../../assets/Characters/WW.OrcShaman.png"),
      "Grokk Bonenawer"               : require("../../assets/Characters/WW.GrokkTheBonenawer.png"),
      "Orc Butcher"                   : require("../../assets/Characters/WW.OrcButcher.png"),
      "Iron Tusk Bronir"              : require("../../assets/Characters/WW.IronTuskBronir.png"),
      "Void bug"                      : require("../../assets/Characters/VS.VoidBug.png"),
      "Void Tentacles"                : require("../../assets/Characters/VS.VoidTentacles.png"),
      "Abyssal mage"                  : require("../../assets/Characters/VS.AbyssalMage.png"),
      "Shadow Hunter"                 : require("../../assets/Characters/VS.ShadowHunter.png"),
      "Void Soldier"                  : require("../../assets/Characters/VS.VoidSoldier.png"),
      "Riftbearer Bellarahn"          : require("../../assets/Characters/VS.RiftbearerBellarahn.png"),
      "World Devourer"                : require("../../assets/Characters/VS.WorldDevourerKrieg_zor.png"),
      "Shadowbound"                   : require("../../assets/Characters/VS.Shadowbound.png"),
      "Darkrift behemoth"             : require("../../assets/Characters/VS.DarkriftBehemoth.png"),
      "Eclipse Scavager"              : require("../../assets/Characters/VS.EclipseScavager.png"),
      "Undead"                        : require("../../assets/Characters/UA.Undead.png"),
      "Zombified Soldier"             : require("../../assets/Characters/UA.ZombifiedSoldier.png"),
      "Putrid Paladin"                : require("../../assets/Characters/UA.PutridPaladin.png"),
      "Rotten Hound"                  : require("../../assets/Characters/UA.RottenHound.png"),
      "Necroman"                      : require("../../assets/Characters/UA.Vex_naTheNecromancer.png"),
      "Rak'khar"                      : require("../../assets/Characters/UA.Rak_khar.png"),
      "Commander"                     : require("../../assets/Characters/UA.CommanderDullahan.png"),
      "Locust Swarm"                  : require("../../assets/Characters/UA.LocustSwarm.png"),
      "Maddened rune"                 : require("../../assets/Characters/UA.MaddenedRuneBearer.png"),
      "Undead Berserkers"             : require("../../assets/Characters/UA.UndeadBerserkers.png"),

      "UNLOCK"            : require("../../assets/Characters/User.png"),
      "PDK": require("../../assets/Developer_/PDK.jpg")
    };
    return imageMap[name] || require("../../assets/Developer_/PDK.jpg");
  };